name: release NuGet
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build with dotnet
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - run: dotnet build SimpleSockets --configuration Release
    - name: Publish nuget
      run: |
           for f in ./[repository]/bin/Release/*.nupkg
           do
            curl -vX PUT -u "[user]:${{ secrets.NUGET_API_KEY }}" -F package=@$f https://nuget.pkg.github.com/[user]/
           done
      shell: bash
